# Generated by Django 5.0.7 on 2024-07-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0003_remove_item_before_price_remove_item_current_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="discount_label",
            field=models.CharField(default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(upload_to="item_images/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="image_hover",
            field=models.ImageField(upload_to="item_images/"),
        ),
        migrations.AlterField(
            model_name="item",
            name="old_price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name="item",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
