# Generated by Django 5.0.7 on 2024-08-10 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("website", "0004_review_delete_blogpost"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="profile_pic",
            field=models.ImageField(
                default="images/default_profile.webp", upload_to="profile_pics/"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="website.item"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="review",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
